### ISSUE TITLE
Consider creating an AMI for spooling up the software dependencies

### ISSUE THREAD

**Issue by wincowgerDEV** [U-Alberta/ADaPT-ML#10]
Hey @nulberry I apologize for my silence for the last few weeks. I realized that I was going to have to create a virtual machine from scratch to get this running on my device and that intimidated me a little because it's beyond the scope of what a normal reviewer would do. Considering that there are so many dependencies for this software (Operating system, Docker, and several other software packages) would you consider creating an Amazon Machine Image or something similar which spools up all dependencies with a single selection of a machine image? That would allow me and users to get going with your workflow at the click of a button.

**Comment by wincowgerDEV** [comment]
If this above doesn't work and you would still like me to review the software functionality then another option could be that we try to get this fully running on Windows. I am currently unable to access linux or macos any other way. Let me know what you think.

**Comment by nulberry** [comment]
Hello again! I read over all of the comments on the JOSS review thread and your comment here, and gleaned from all of it that I first of all needed to improve the documentation for getting started with ADaPT-ML on Windows. I hope that the instructions in my latest commit b8de60ad59b42684f9cf33e4ea931789efa9ed3d are now clear. I followed them myself to test ADaPT-ML on my personal Windows machine, so I am confident that they should work for the majority of Windows users. Here are the highlights:

In `usage.md`:
- got rid of the Required and Recommended Setup sections, because I think they incorrectly implied that this software wouldn't work the same and/or wasn't fully fleshed out on Windows.
- specified that Windows users can download and install Docker Desktop, which will include Docker Compose.
- found Windows-specific instructions for ensuring CrateDB passes its bootstrap checks.

In `test/README.md`:
- replaced the Terminal output from `docker-compose ps` with the Command Line output to match what Windows users will see.
- fixed the deployment testing instructions (didn't realize they were outdated until I tried them out on Windows, so I'm glad that this has been caught!).

Please let me know how following these improved instructions works out. It was my goal from the start of this project to make sure that ADaPT-ML could run on Mac, Linux, and Windows, with tools like Docker that ensure everything works the same across platforms.

**Comment by wincowgerDEV** [comment]
Thanks for clarifying your goals here and improving the documentation and
trying out the windows workflow on your own machine. I'll give this new
instructions a shot soon.

Warm Regards
Win

**Comment by wincowgerDEV** [comment]
I went through the `usage.md` doc today and got stopped at this point:
"Check to make sure there is >20 GB in your Docker root directory ([this thread](https://stackoverflow.com/questions/42250222/where-is-docker-image-location-in-windows-10) might help you find it) for storing images"
I read through the StackOverflow and tried the most upvoted responses and none of them worked. Is there another way to increase the size of the root directory?

**Comment by wincowgerDEV** [comment]
P.S. it might be a good idea to also recommend following the instructions to change WSL2 to the default when downloading WSL2.

**Comment by nulberry** [comment]
Are you experiencing the same problem that you were before in issue #7 ? Specifically, the problem with running out of memory?

> New issue on this same thread, the docker image failed to load completely because it ran out of memory: I got this error, failed to register layer: Error processing tar file(exit status 1),
> 
> looks like it has to do with the virtual machine setup on the windows device [moby/moby#32811](https://github.com/moby/moby/issues/32811)
> 
> Current system I am on: 
> ![image](https://user-images.githubusercontent.com/26821843/150239093-01f9a59d-3f5c-43d4-92aa-478c95e34a9e.png)

What is the output of `docker system df` for you? This is mine:
```
docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          30        11        63.21GB   46.87GB (74%)
Containers      17        10        5.986GB   5.985GB (99%)
Local Volumes   1         1         18.97kB   0B (0%)
Build Cache     0         0         0B        0B
```
Verbose shows more detail, `docker system df -v`:
```
Images space usage:

REPOSITORY                          TAG               IMAGE ID       CREATED         SIZE      SHARED SIZE   UNIQUE SIZE   CONTAINERS
nullberry/adapt-ml-ls               latest            9c934f91fabe   3 months ago    594.3MB   114.3MB       480MB         1
nullberry/adapt-ml-dp               latest            043d88b0e93e   4 months ago    4.469GB   763.8MB       3.705GB       1
nullberry/adapt-ml-m-deploy         latest            a804529f7dff   5 months ago    1.518GB   1.518GB       8.562kB       1
nullberry/adapt-ml-dp-web           latest            7f0588580cd3   5 months ago    417MB     133.1MB       283.9MB       2
nullberry/adapt-ml-m                latest            a52aa40e80c4   5 months ago    10.37GB   770.4MB       9.597GB       1
```
These are the 5 images that docker-compose pulls for ADaPT-ML. Unfortunately `docker system df` doesn't show how much space there is in the directory for images itself, and I do not know of a docker command that does this, hence the link to the StackOverflow thread. 

I think that if there isn't adequate space, you would have to relocate the root directory. I'm sorry, I know this doesn't really answer your question, I'm just not too sure how to proceed if the installation of Docker Desktop completed normally with the root directory placed in the default spot but there isn't enough space for the ~15GB worth of images.

**Comment by wincowgerDEV** [comment]
No I haven't gotten to that point this time I'm just following the
instructions and got stuck because they aren't clear there what I should do
so I was flagging it for improved documentation. Should I proceed without
making that check?

**Comment by wincowgerDEV** [comment]
I tried to skip ahead since I couldn't verify that the root had enough space. Then I edited the WSL config file. Then I followed the startup instructions for testing and when I input `docker-compose --env-file .env --profile dev up -d` I received this error message which I am not sure what it is from. 

error during connect: Get "https://192.168.99.100:2376/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dadapt-ml-main%22%3Atrue%7D%7D&limit=0": dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by nulberry** [comment]
I think I might move the step for checking space in the root directory to a troubleshooting section because I'd imagine that checking the space is only necessary if people run into issues. Do you think this is fair? 

I found [this thread](https://forums.docker.com/t/docker-starts-but-trying-to-do-anything-results-in-error-during-connect/49007/5) where a person had a similar error message, and it was due to a conflict between Docker Toolbox, Docker for Windows, and VirtualBox. Would you be comfortable performing these steps and starting the setup process again from the beginning? 

> P.S. it might be a good idea to also recommend following the instructions to change WSL2 to the default when downloading WSL2.

I can certainly add more detail to this step in the documentation. I'll specify that users need to follow steps 4-6; I was actually wondering this myself when I was following the prompt from Docker Desktop when I first installed it so I think it would be a good thing to add.

**Comment by nulberry** [comment]
In my latest commit, cab3c4834484fc2a1ddc346489e16c6ae5709e18, I added a batch file to automatically run the Windows tests, added a troubleshooting section to the testing documentation, and specified that people need to follow steps 4-6 of the WSL documentation.

**Comment by wincowgerDEV** [comment]
Thanks for this, trying it out again.

**Comment by wincowgerDEV** [comment]
> I found [this thread](https://forums.docker.com/t/docker-starts-but-trying-to-do-anything-results-in-error-during-connect/49007/5) where a person had a similar error message, and it was due to a conflict between Docker Toolbox, Docker for Windows, and VirtualBox. Would you be comfortable performing these steps and starting the setup process again from the beginning?


Following these instructions worked to resolve that error, thank you

**Comment by wincowgerDEV** [comment]
Alright sweet, I got to the point where I am using the batch file now.
Here is the output of what I see in the console. From the documentation, I don't know if it is ok that I got two errors, one for starting modeling tests and one for deployment tests but then it says that everything was successful?
![image](https://user-images.githubusercontent.com/26821843/156092885-694ee8dc-b457-4087-a038-4911b2b61f28.png)

**Comment by wincowgerDEV** [comment]
I did check all the ports for label studio, crateDB, and MLFlow and they appear to be running.

**Comment by nulberry** [comment]
Hey, sorry for the late response to this. If you have a chance to come back to this and maybe try running the tests again, did you check the container status, `docker-compose ps`, and the container logs, `docker logs <container_name>`? I'm guessing that it has something to do with maybe the MLflow databases not being fully ready when the tests were run, but it's hard to say without seeing more information. Thanks!

**Comment by wincowgerDEV** [comment]
That might be it, looks like the a few of the containers have "starting" status at first but I gave them a little time and now they are healthy. 

![image](https://user-images.githubusercontent.com/26821843/156937612-73cc3db9-8bd6-4e51-b532-9bf6bbb433da.png)
![image](https://user-images.githubusercontent.com/26821843/156937653-9e8d1a92-2c73-4096-ad82-f81da1bd19e9.png)

Ok running the bat file again. Looks great! Thank you, closing this issue now. 
![image](https://user-images.githubusercontent.com/26821843/156937771-07b13047-a61d-40c7-93ed-ca8d48035402.png)
